/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sisloj;

import br.senai.sc.sisloj.views.CadastroCliente;
import br.senai.sc.sisloj.views.ListagemCliente;

import br.senai.sc.sisloj.views.PainelRosa;
import br.senai.sc.sisloj.views.PainelAmarelo;
import br.senai.sc.sisloj.views.PainelInicial;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class SisLojFrame extends javax.swing.JFrame {

    /**
     * Creates new form SisLojFrame
     */
    public SisLojFrame() {
        initComponents();
        
        PainelInicial pInicial =new PainelInicial();
        PainelRosa pRosa = new PainelRosa();
       PainelAmarelo pAmarelo = new PainelAmarelo();
     CadastroCliente cadastro = new CadastroCliente();
     
     
     
       painelPrincipal.add(cadastro,"cadastrarCliente");
       painelPrincipal.add(pInicial,"painelInicial");
       painelPrincipal.add(pRosa,"painelRosa");
       painelPrincipal.add(pAmarelo,"painelAmarelo");
     
       CardLayout cl =(CardLayout) painelPrincipal.getLayout();
       cl.show(painelPrincipal, "painelInicial");
       this.setExtendedState(MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        menuCadastrarCliente = new javax.swing.JMenuItem();
        menuListarCliente = new javax.swing.JMenuItem();
        painelColorido = new javax.swing.JMenu();
        rosa = new javax.swing.JMenuItem();
        amarelo = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuCadastroProduto = new javax.swing.JMenuItem();
        menuListarProdutos = new javax.swing.JMenuItem();
        menuProdutosEmFalta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para gestao de loja");
        setMaximumSize(new java.awt.Dimension(100, 50));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        painelPrincipal.setMaximumSize(new java.awt.Dimension(500, 500));
        painelPrincipal.setPreferredSize(new java.awt.Dimension(500, 800));
        painelPrincipal.setLayout(new java.awt.CardLayout());

        barraDeMenu.setPreferredSize(new java.awt.Dimension(45, 45));

        menuCliente.setText("Cliente");
        menuCliente.setMaximumSize(new java.awt.Dimension(45, 45));

        menuCadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuCadastrarCliente.setText("Cadastrar cliente");
        menuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuCadastrarCliente);

        menuListarCliente.setText("Listar clientes");
        menuListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuListarCliente);

        barraDeMenu.add(menuCliente);

        painelColorido.setText("Paineis colorido");
        painelColorido.setMaximumSize(new java.awt.Dimension(45, 45));

        rosa.setText("Rosa");
        rosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosaActionPerformed(evt);
            }
        });
        painelColorido.add(rosa);

        amarelo.setText("Amarelo");
        amarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amareloActionPerformed(evt);
            }
        });
        painelColorido.add(amarelo);

        barraDeMenu.add(painelColorido);

        menuProduto.setText("Produto");
        menuProduto.setMaximumSize(new java.awt.Dimension(45, 45));
        menuProduto.setPreferredSize(new java.awt.Dimension(45, 45));

        menuCadastroProduto.setText("Cadastrar produtos");
        menuProduto.add(menuCadastroProduto);

        menuListarProdutos.setText("Listar produtos");
        menuProduto.add(menuListarProdutos);

        menuProdutosEmFalta.setText("Produtos em falta");
        menuProduto.add(menuProdutosEmFalta);

        barraDeMenu.add(menuProduto);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarClienteActionPerformed
       CardLayout cl =(CardLayout) painelPrincipal.getLayout();
       cl.show(painelPrincipal, "cadastrarCliente");
    }//GEN-LAST:event_menuCadastrarClienteActionPerformed

    private void rosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosaActionPerformed
       CardLayout cl =(CardLayout) painelPrincipal.getLayout();
       cl.show(painelPrincipal, "painelRosa");
    }//GEN-LAST:event_rosaActionPerformed

    private void amareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amareloActionPerformed
       CardLayout cl =(CardLayout) painelPrincipal.getLayout();
       cl.show(painelPrincipal, "painelAmarelo");
    }//GEN-LAST:event_amareloActionPerformed

    private void menuListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarClienteActionPerformed
      ListagemCliente lisCli =new ListagemCliente();
          painelPrincipal.add(lisCli,"listaCliente");
        CardLayout cl =(CardLayout) painelPrincipal.getLayout();
       cl.show(painelPrincipal, "listaCliente");
    }//GEN-LAST:event_menuListarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisLojFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem amarelo;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem menuCadastrarCliente;
    private javax.swing.JMenuItem menuCadastroProduto;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuListarCliente;
    private javax.swing.JMenuItem menuListarProdutos;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenuItem menuProdutosEmFalta;
    private javax.swing.JMenu painelColorido;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JMenuItem rosa;
    // End of variables declaration//GEN-END:variables
}
